# docker-compose.yml

version: '3.8' # 최신 버전 중 하나를 사용합니다.

services:
  gpu-checker:
    # 현재 디렉토리의 Dockerfile을 사용하여 이미지를 빌드합니다.
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpu_checker_container
    # NVIDIA Container Toolkit을 사용하여 GPU 접근을 활성화합니다.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # 'all'은 사용 가능한 모든 GPU를 할당합니다. 특정 개수를 원하면 숫자로 변경 (예: count: 1)
              count: all
              # GPU 기능을 사용하도록 명시합니다.
              capabilities: [gpu]
    # Docker < 19.03 및 nvidia-docker2 구버전 사용 시 필요할 수 있음 (현재는 deploy.resources 권장)
    # runtime: nvidia